name: continuous-integration

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: npm run check
  run:
    name: run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx tsc
      - run: npm install
        working-directory: ./sample
      - run: npx tsc
        working-directory: ./sample
      - run: node index.js
        working-directory: ./sample
