name: user-installation

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
      fail-fast: false
    defaults:
      run:
        working-directory: ./sample
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm uninstall class-transform
      - run: npm install class-transform
      - run: node index.js
